export const QUERY_BANGUMI = 'QUERY_BANGUMI'
export const RECEIVE_BANGUMI_DATA = 'RECEIVE_BANGUMI_DATA'
export const GET_BANGUMI_DATA_BY_DAY = 'GET_BANGUMI_DATA_BY_DAY'
export const SWITCH_TAB = 'SWITCH_TAB'
